[package]
edition = "2021"
name = "ferrispot"
version = "0.1.0"

[dependencies]
base64 = "0.13.0"
rand = "0.8.5"
reqwest = {version = "0.11.11", features = ["blocking", "json"]}
serde = {version = "1.0.138", features = ["derive"]}
thiserror = "1.0.31"

[dev-dependencies]
dotenvy = "0.15.1"
